package com.smart.desktop.databases;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.smart.desktop.core.bean.UserInfo;
import com.smart.desktop.core.bean.TransRecord;

import com.smart.desktop.databases.UserInfoDao;
import com.smart.desktop.databases.TransRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig transRecordDaoConfig;

    private final UserInfoDao userInfoDao;
    private final TransRecordDao transRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        transRecordDaoConfig = daoConfigMap.get(TransRecordDao.class).clone();
        transRecordDaoConfig.initIdentityScope(type);

        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        transRecordDao = new TransRecordDao(transRecordDaoConfig, this);

        registerDao(UserInfo.class, userInfoDao);
        registerDao(TransRecord.class, transRecordDao);
    }
    
    public void clear() {
        userInfoDaoConfig.clearIdentityScope();
        transRecordDaoConfig.clearIdentityScope();
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public TransRecordDao getTransRecordDao() {
        return transRecordDao;
    }

}
