package com.smart.desktop.databases;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.smart.desktop.core.bean.TransRecord;
import com.smart.desktop.core.bean.UserInfo;

import com.smart.desktop.databases.TransRecordDao;
import com.smart.desktop.databases.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig transRecordDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final TransRecordDao transRecordDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        transRecordDaoConfig = daoConfigMap.get(TransRecordDao.class).clone();
        transRecordDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        transRecordDao = new TransRecordDao(transRecordDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(TransRecord.class, transRecordDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        transRecordDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public TransRecordDao getTransRecordDao() {
        return transRecordDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
